import 'dart:io';

/// Генератор interview_questions.md + interview_answers.md для модулей.
void main() {
  final root = Directory(r'd:\MyPrograms\flutter_dart_learn');
  final modules = <String, _Qa>{
    '1_dart_core/null_safety': _nullSafety,
    '1_dart_core/oop': _oop,
    '1_dart_core/generics': _generics,
    '1_dart_core/List': _list,
    '1_dart_core/map_set': _mapSet,
    '1_dart_core/strings': _strings,
    '1_dart_core/json': _json,
    '1_dart_core/dart3_patterns': _patterns,
    '1_dart_core/eventloop': _eventLoop,
    '2_dart_async/future': _future,
    '2_dart_async/streams': _streams,
    '2_dart_async/isolates': _isolates,
    '3_functional_dart_with_fpdart/fpdart': _fpdart,
    '4_flutter_ui_basics': _flutterWidgets,
    '4_flutter_ui_basics/constraints': _constraints,
    '4_flutter_ui_basics/layout': _layout,
    '4_flutter_ui_basics/scrolling': _scrolling,
    '4_flutter_ui_basics/images': _images,
    '4_flutter_ui_basics/forms': _forms,
    '4_flutter_ui_basics/overlays': _overlays,
    '4_flutter_ui_basics/theming': _theming,
    '4_flutter_ui_basics/widget_keys': _widgetKeys,
    '4_flutter_ui_basics/animations': _animations,
    '5_flutter_app_skills/navigation': _navigation,
    '5_flutter_app_skills/responsive': _responsive,
    '5_flutter_app_skills/accessibility': _a11y,
    '5_flutter_app_skills/focus': _focus,
    '5_flutter_app_skills/networking': _networking,
    '5_flutter_app_skills/local_storage': _storage,
    '5_flutter_app_skills/local_notifications': _notifications,
    '5_flutter_app_skills/push_notifications': _pushNotifications,
    '5_flutter_app_skills/permissions': _permissions,
    '5_flutter_app_skills/app_lifecycle': _lifecycle,
    '5_flutter_app_skills/deep_links': _deepLinks,
    '5_flutter_app_skills/localization': _localization,
    '5_flutter_app_skills/errors_juniors': _errorsJuniors,
    '6_state_management/change_notifier': _changeNotifier,
    '6_state_management/architecture': _architecture,
    '6_state_management/riverpod': _riverpod,
    '6_state_management/fpdart_riverpod': _fpdartRiverpod,
    '8_prompt_engineering': _promptEngineering,
    '10_mini_apps': _miniApps,
  };

  for (final entry in modules.entries) {
    final dir = Directory('${root.path}\\${entry.key.replaceAll('/', '\\')}');
    dir.createSync(recursive: true);
    final q = entry.value;
    File('${dir.path}\\interview_questions.md').writeAsStringSync(
      '# Вопросы с собеседований: ${q.title}\n\n'
      'Сначала ответь сам, потом сверься с `interview_answers.md`.\n\n'
      '${[
        for (var i = 0; i < q.items.length; i++) '${i + 1}. ${q.items[i].q}'
      ].join('\n')}\n',
    );
    File('${dir.path}\\interview_answers.md').writeAsStringSync(
      '# Ответы: ${q.title}\n\n'
      '${[
        for (var i = 0; i < q.items.length; i++)
          '**${i + 1}.** ${q.items[i].a}'
      ].join('\n\n')}\n',
    );
    stdout.writeln('OK ${entry.key}');
  }
}

class _Item {
  const _Item(this.q, this.a);
  final String q;
  final String a;
}

class _Qa {
  const _Qa(this.title, this.items);
  final String title;
  final List<_Item> items;
}

const _nullSafety = _Qa('Null Safety', [
  _Item('Что такое null safety в Dart и чем отличается от TypeScript?',
      'В Dart типы по умолчанию non-nullable. `T?` — nullable. Нет `undefined`. Операторы `?.`, `??`, `??=`, `!`. Flow analysis промоутит тип после проверки на null.'),
  _Item('Когда допустим оператор `!`?',
      'Только когда вы доказали себе, что значение не null (или после проверки, которую анализатор не видит). Иначе — runtime crash. На собеседовании лучше говорить: предпочитаю `??` / early return / promotion.'),
  _Item('Что такое definite assignment и `late`?',
      '`late` откладывает инициализацию. `late final` — один раз. Если прочитать до записи — runtime error. Нужен, когда поле нельзя сделать nullable, но инициализация не в конструкторе.'),
  _Item('Как работает promotion для локальных переменных vs полей?',
      'Локальные переменные промоутятся после `if (x != null)`. Поля класса — нет (могут измениться Concurrently), поэтому копируют в локальную `final v = field;`.'),
  _Item('Разница `??` и `?.`?',
      '`?.` — безопасный вызов метода/доступа. `??` — выбор значения, если левый операнд null.'),
  _Item('Что вернёт `list?.first` для null-списка и пустого списка?',
      'Для `null` — `null`. Для пустого — throw `StateError` (first на пустом списке).'),
  _Item('Зачем `required` на named-параметрах?',
      'Делает named-параметр обязательным при null safety; без default нельзя вызвать, не передав значение.'),
  _Item('Как безопасно работать с `Map` lookup?',
      '`map[key]` всегда `V?`. Нельзя считать non-null без проверки. Используйте `containsKey`, `??`, pattern matching.'),
]);

const _oop = _Qa('OOP в Dart', [
  _Item('Чем `factory` конструктор отличается от обычного?',
      'Может вернуть существующий экземпляр, подтип или бросить ошибку; не обязан создавать новый объект через `this`.'),
  _Item('`abstract class` vs `interface` / `implements`?',
      '`extends` — наследование реализации (один родитель). `implements` — контракт API, реализуете все члены. С Dart 3 есть `interface class` / `abstract interface class`.'),
  _Item('Что такое mixin и когда использовать `with`?',
      'Переиспользуемое поведение без полного наследования. Подмешивается через `with`. Нельзя создать экземпляр mixin.'),
  _Item('Как правильно переопределить `==` и `hashCode`?',
      'Переопределять вместе. Equal objects → equal hashCode. Для value-объектов сравнивают поля. Иначе ломаются `Set`/`Map`.'),
  _Item('Что такое const constructor?',
      'Создаёт canonicalized compile-time константу. Все поля `final`, аргументы const. Экономит память и даёт identical.'),
  _Item('Named vs generative constructors?',
      'Обычный generative инициализирует экземпляр. Named — альтернативные точки входа (`User.fromJson`). `factory` — особый случай.'),
  _Item('Зачем `sealed class`?',
      'Ограничивает иерархию одним library; включает exhaustiveness checking в switch.'),
  _Item('Можно ли наследовать от нескольких классов?',
      'Нет multiple inheritance классов. Композиция: `implements` + `with` mixins.'),
]);

const _generics = _Qa('Generics и Extensions', [
  _Item('Зачем generics в Dart?',
      'Типобезопасные коллекции и API без потери типа (`List<int>` вместо `List<dynamic>`).'),
  _Item('Что значит `T extends num`?',
      'Ограничение type parameter: `T` — подтип `num`, можно вызывать API числа.'),
  _Item('Что такое extension methods?',
      'Добавление методов/геттеров к существующему типу без изменения класса. Синтаксический сахар, не ломает инкапсуляцию private.'),
  _Item('Extension видит private члены типа?',
      'Только если extension в той же library, что и тип.'),
  _Item('Разница `List<T?>` и `List<T>?`?',
      '`List<T?>` — список есть, элементы могут быть null. `List<T>?` — сам список может быть null.'),
  _Item('Что такое covariance у generics в Dart?',
      '`List<Dog>` не всегда безопасен как `List<Animal>` при записи. Чтение ковариантно, запись опасна — runtime check.'),
  _Item('Как сделать generic repository?',
      '`abstract interface class Repo<T> { T? getById(String id); }` + реализация с `Map<String, T>`.'),
  _Item('Зачем `typedef` с generics?',
      'Короткие алиасы: `typedef JsonMap = Map<String, dynamic>;` / `typedef Mapper<T,R> = R Function(T);`.'),
]);

const _list = _Qa('List', [
  _Item('`List` vs `Iterable`?',
      '`Iterable` — ленивый обход. `List` — индексный доступ, изменяемая/фиксированная длина, `length` O(1).'),
  _Item('`map` на List возвращает List?',
      'Нет, `Iterable`. Нужен `.toList()` если нужен список.'),
  _Item('Разница `growable` и fixed-length list?',
      '`List.filled(n, e, growable: false)` — нельзя add/remove. Growable — обычный `[]`.'),
  _Item('Как эффективно удалять по условию?',
      '`removeWhere`, или фильтр в новый список. Не мутировать во время `for-in` неаккуратно.'),
  _Item('Что делает `expand` / `fold` / `reduce`?',
      '`expand` — flatMap. `fold` — аккумулятор с начальным. `reduce` — без начального, на пустом бросает.'),
  _Item('Сложность `contains` у List?',
      'O(n). Для частых проверок — `Set`.'),
  _Item('Как безопасно взять элемент по индексу?',
      'Проверить `index < length` или `elementAtOrNull` (collection package) / свой helper.'),
  _Item('Collection-if / collection-for — что это?',
      'В литералах: `[if (x) a, for (final e in list) e * 2]`.'),
]);

const _mapSet = _Qa('Map и Set', [
  _Item('Чем `Map` отличается от `Set`?',
      '`Map` — ключ→значение. `Set` — уникальные элементы. Оба на hash (по умолчанию LinkedHash*).'),
  _Item('Почему важен `hashCode`/`==` для ключей Map?',
      'Хэш-таблица ищет бакет по hashCode, сравнивает через `==`. Несогласованность — «пропавшие» ключи.'),
  _Item('`map[key] = value` vs `putIfAbsent`?',
      '`[]=` всегда пишет. `putIfAbsent` вычисляет значение только если ключа нет.'),
  _Item('Итерация Map сохраняет порядок?',
      'У `LinkedHashMap` (default) — порядок вставки. `HashMap` — нет гарантии.'),
  _Item('Как посчитать частоты элементов?',
      '`for` + `map[e] = (map[e] ?? 0) + 1` или `fold`.'),
  _Item('Пересечение / объединение Set?',
      '`intersection`, `union`, `difference`.'),
  _Item('Можно ли мутировать ключ после вставки в Map?',
      'Опасно: hashCode может измениться, ключ «потеряется». Ключи должны быть immutable value.'),
  _Item('`containsKey` vs `map[key] != null`?',
      'Значение само может быть null (если `V?`). `containsKey` точнее для наличия ключа.'),
]);

const _strings = _Qa('Strings и RegExp', [
  _Item('Строки в Dart изменяемые?',
      'Нет, immutable. Конкатенация создаёт новые объекты; для сборки — `StringBuffer`.'),
  _Item(r'Интерполяция: когда `$a` и `${a.b}`?',
      r'Простой идентификатор — `$name`. Выражение — `${obj.field}`.'),
  _Item('`substring` vs `slice` аналог?',
      '`substring(start, end)`, `replaceRange`. Осторожно с рунами/эмодзи: лучше `characters` package.'),
  _Item('Как работает RegExp в Dart?',
      '`RegExp(pattern)`, `hasMatch`, `firstMatch`, `allMatches`, groups через `Match`.'),
  _Item('Multiline / case-sensitive флаги?',
      '`RegExp(..., multiLine: true, caseSensitive: false, dotAll: true)`.'),
  _Item('Как экранировать пользовательский ввод в RegExp?',
      '`RegExp.escape(userInput)`.'),
  _Item('UTF-16 и code units — в чём риск?',
      '`length` считает UTF-16 code units, не графемы. Суррогатные пары ломают наивный index.'),
  _Item('`trim`, `padLeft`, `split` — типичные задачи?',
      'Нормализация ввода, форматирование, CSV/query parsing.'),
]);

const _json = _Qa('JSON и модели', [
  _Item('Как парсить JSON без codegen?',
      '`jsonDecode` → `Map`/`List` → ручной `fromJson`. Ошибки типов → `FormatException`.'),
  _Item('Почему `Map<String, dynamic>`?',
      'JSON значения неоднородны: num/String/bool/List/Map/null.'),
  _Item('`json_serializable` vs ручной fromJson?',
      'Codegen меньше boilerplate и ошибок; ручной — контроль и понимание на mid-собесе.'),
  _Item('Как моделировать optional поля?',
      '`T?`, отсутствие ключа и explicit null. Документировать контракт API.'),
  _Item('Вложенные объекты и списки?',
      'Рекурсивно `Child.fromJson`, `list.map(E.fromJson).toList()` с проверкой типа.'),
  _Item('DateTime из JSON?',
      'Обычно ISO-8601 string → `DateTime.parse`. Учитывать UTC/local.'),
  _Item('Что делать с неизвестными enum значениями?',
      '`switch` + fallback / throw / `unknown` case — по политике API compatibility.'),
  _Item('Зачем DTO отдельно от domain entity?',
      'JSON/API форма меняется чаще домена; маппинг в data-слое изолирует UI/domain.'),
]);

const _patterns = _Qa('Patterns, Records, Sealed', [
  _Item('Что такое record в Dart 3?',
      'Неизменяемый агрегатный тип `(int, String)` / named record fields без отдельного class.'),
  _Item('Pattern matching в switch — зачем?',
      'Деструктуризация и exhaustiveness на sealed/enum. Меньше boilerplate `is` + cast.'),
  _Item('`if-case` vs `if (x is T)`?',
      '`if (x case int n when n > 0)` — паттерн + объявление + when в одном.'),
  _Item('Object patterns?',
      '`case User(:final name, :final age)` достаёт поля.'),
  _Item('Зачем sealed + switch?',
      'Компилятор требует покрыть все подтипы — безопасный рефакторинг.'),
  _Item('Destructuring list/map patterns?',
      r'`case [first, ...rest]`, `case {"id": int id}`.'),
  _Item('Когда record лучше class?',
      'Локальные пары/тройки без поведения. Для домена с методами/инвариантами — class.'),
  _Item('Exhaustiveness и default?',
      'На sealed лучше без default — иначе потеряете предупреждение о новом case.'),
]);

const _eventLoop = _Qa('Event Loop', [
  _Item('Как устроен event loop в Dart?',
      'Один UI/main isolate: sync код → microtask queue → event queue. Microtasks всегда раньше следующих events.'),
  _Item('Что попадает в microtask queue?',
      '`scheduleMicrotask`, завершение `Future` (then), `Future.microtask`.'),
  _Item('Что попадает в event queue?',
      '`Future.delayed`, timer, I/O, user events, `Future(() => ...)`.'),
  _Item('Почему долгий sync цикл фризит UI?',
      'Event loop не обрабатывает кадры/events, пока sync код не закончится.'),
  _Item('Порядок: print sync, Future, scheduleMicrotask?',
      'Сначала sync, потом все microtasks, потом events (Future).'),
  _Item('`async` функция сразу возвращает Future?',
      'Да. Тело до первого await выполняется sync в текущем turn; продолжение — позже.'),
  _Item('Связь с Flutter frames?',
      'Каждый frame — события на event queue. Тяжёлая работа → jank → isolates/compute.'),
  _Item('Можно ли starvation microtasks?',
      'Да, бесконечная постановка microtasks не даст обработать events.'),
]);

const _future = _Qa('Future', [
  _Item('Future vs Promise (JS)?',
      'Концептуально похожи. В Dart `async/await`, `Future.wait`, `whenComplete`, типизация `Future<T>`.'),
  _Item('`Future.wait` vs последовательный await?',
      '`wait` параллелит. Последовательный await — сумма задержек.'),
  _Item('Как обработать ошибки Future?',
      '`try/catch` с await, `.catchError`, `.onError`, `TimeoutException` через `timeout`.'),
  _Item('Что такое uncompleted Future?',
      'Ещё нет результата. `Completer` позволяет завершить вручную.'),
  _Item('`Future.value` / `Future.error` / `Future.delayed`?',
      'Уже завершённый success/error; delayed планирует в event queue.'),
  _Item('Почему нельзя «забыть» Future в Flutter?',
      'Ошибки без await/catch могут стать unreported; UI не дождётся результата. Используйте `unawaited` осознанно.'),
  _Item('`then` vs `await`?',
      '`await` читаемее и лучше со stack traces в async. `then` — цепочки/низкий уровень.'),
  _Item('Cancellation Future?',
      'У самого Future нет cancel. Паттерны: флаги, `CancelableOperation` (async package), abort контроллеры.'),
]);

const _streams = _Qa('Streams', [
  _Item('Single-subscription vs broadcast?',
      'Single — один слушатель, события с буферизацией до listen. Broadcast — много слушателей, без «прошлых» событий.'),
  _Item('Зачем StreamController?',
      'Создать свой поток: `add`, `addError`, `close`. Есть sync/async версии.'),
  _Item('Как не забыть отписку?',
      'Хранить `StreamSubscription` и `cancel` в dispose. `await for` выходит при break/cancel.'),
  _Item('`async*` / `yield` / `yield*`?',
      'Генерация Stream. `yield` — элемент, `yield*` — проксирует другой stream/iterable.'),
  _Item('Backpressure — что знаете?',
      'Производитель быстрее потребителя. Стратегии: pause subscription, буфер, drop, isolate.'),
  _Item('Transformers: map/where/expand/debounce?',
      'Ленивые преобразования потока. Debounce часто через `rxdart` или ручной Timer.'),
  _Item('Stream vs Future?',
      'Future — 1 результат. Stream — 0..N событий во времени.'),
  _Item('Как тестировать Stream?',
      '`expectLater(stream, emitsInOrder([...]))` из `matcher` / flutter_test.'),
]);

const _isolates = _Qa('Isolates', [
  _Item('Почему в Dart нет shared-memory threads?',
      'Isolates не делят память → без data races. Общение через сообщения (SendPort/ReceivePort).'),
  _Item('Когда выносить в isolate?',
      'CPU-тяжёлое: большой JSON, image processing, crypto. Не для микро-задач (накладные расходы).'),
  _Item('`Isolate.run` vs `compute` (Flutter)?',
      'Оба запускают one-shot функцию в isolate. `compute` — Flutter helper; `Isolate.run` — чистый Dart.'),
  _Item('Что нельзя передавать между isolates?',
      'UI-объекты, `BuildContext`, большинство live callbacks с захватом UI, многие native resources.'),
  _Item('Что можно передавать?',
      'Примитивы, простые List/Map, SendPort, объекты по copyable правилам (на практике — «простые данные»).'),
  _Item('Как устроен долгоживущий worker?',
      'Spawn isolate, обмен портами, цикл обработки сообщений, явный kill/shutdown.'),
  _Item('Ошибки в isolate?',
      'Пробрасываются в Future от `Isolate.run` / требуют обработки на портах worker-а.'),
  _Item('Изоляты и Flutter plugins?',
      'Не все плагины thread-safe; UI и platform channels обычно на main isolate.'),
]);

const _fpdart = _Qa('fpdart (Option, Either, TaskEither)', [
  _Item('Зачем Option вместо null?',
      'Явное отсутствие значения в типе. Заставляет обработать None через map/fold/getOrElse.'),
  _Item('Either vs exceptions?',
      'Ошибка — значение Left, часть сигнатуры. Легче композировать и тестировать, чем try/catch сквозь слои.'),
  _Item('Task vs Future?',
      '`Task` — lazy описание async (запуск через `run`). Future стартует сразу при создании.'),
  _Item('TaskEither — типичный use-case?',
      'Repository/API: async + доменные ошибки без исключений в UI.'),
  _Item('map vs flatMap (bind)?',
      '`map` меняет Right/Some. `flatMap` — цепочка вычислений, которые сами возвращают Option/Either.'),
  _Item('Как накопить несколько ошибок валидации?',
      '`Either<List<String>, T>` / Validated-подход, не fail-fast flatMap.'),
  _Item('traverse/sequence — что это?',
      'Список эффектов → эффект списка. Любой None/Left валит весь результат (обычно).'),
  _Item('IO / Reader / State в fpdart — кратко?',
      'IO — sync эффект. Reader — зависимость из контекста. State — вычисление с состоянием. На практике чаще Option/Either/TaskEither.'),
  _Item('Как стыковать fpdart с UI?',
      'На границе presentation: `fold` / convert в `AsyncValue` / ViewState. UI не импортирует детали data.'),
  _Item('tryCatch в TaskEither?',
      'Оборачивает Future/throwing код в Left через mapper исключения.'),
]);

const _flutterWidgets = _Qa('Flutter Widgets (база)', [
  _Item('StatelessWidget vs StatefulWidget?',
      'Stateless — конфиг без локального мутабельного state. Stateful — `State` с `setState`, lifecycle.'),
  _Item('Что происходит в `build`?',
      'Описание UI (immutable widget tree). Должен быть pure относительно side effects; тяжёлое/async — не сюда.'),
  _Item('InheritedWidget / context.dependOnInheritedWidget?',
      'Проброс данных вниз по дереву; подписчики ребилдятся при изменении.'),
  _Item('`const` виджеты — зачем?',
      'Переиспользование элементов, меньше rebuild work, canonical instances.'),
  _Item('FutureBuilder антипаттерн?',
      'Создавать Future прямо в `build` — перезапуск на каждый rebuild. Создавать в `initState`/провайдере.'),
  _Item('Ключи в списках?',
      'Стабильная идентичность элементов при reorder/filter — `ValueKey(id)`, не index.'),
  _Item('Navigator 1.0 кратко?',
      '`push`/`pop` + `MaterialPageRoute`. Для сложных графов — go_router (declarative).'),
  _Item('Как показать SnackBar/Dialog правильно?',
      'Через `ScaffoldMessenger` / `showDialog` после того, как дерево готово; не в сыром `initState` без post-frame.'),
]);

const _constraints = _Qa('Layout Constraints', [
  _Item('Главное правило constraints в Flutter?',
      'Constraints go down, sizes go up, parent sets position. Родитель говорит «минимум/максимум», ребёнок выбирает размер.'),
  _Item('Tight vs loose vs unbounded?',
      'Tight: min==max. Loose: min=0, max конечен. Unbounded: max=infinity (часто в scroll/flex cross mistakes).'),
  _Item('Почему ListView в Column без Expanded падает?',
      'Column даёт unbounded высота по main axis → ListView хочет бесконечность → ошибка.'),
  _Item('Expanded/Flexible когда нельзя?',
      'Внутри родителя с unbounded main axis (например, ListView children без ограничения).'),
  _Item('`shrinkWrap: true` — цена?',
      'Считает размер всех детей; плохо для длинных списков. Лучше Expanded/фиксированная высота.'),
  _Item('BoxConstraints.tighten?',
      'Сжимает constraints к конкретному размеру в пределах min/max.'),
  _Item('Как дебажить overflow?',
      'Читать RenderFlex overflow, желто-чёрные полосы; проверить Expanded/Flexible/scroll, длины текста.'),
  _Item('LayoutBuilder vs MediaQuery?',
      'LayoutBuilder — constraints родителя. MediaQuery — размер экрана/view insets. Для adaptive внутри слота — чаще LayoutBuilder.'),
]);

const _layout = _Qa('Layout виджеты', [
  _Item('Row/Column: main vs cross axis?',
      'Main — направление Row→горизонт, Column→вертикаль. Cross — перпендикуляр. Align через MainAxisAlignment/CrossAxisAlignment.'),
  _Item('Stack и Positioned?',
      'Наложение детей. Positioned привязывает к краям Stack. Без Positioned — по alignment.'),
  _Item('Expanded vs Flexible?',
      'Оба в Flex. Expanded = Flexible(fit: tight) занимает оставшееся. Flexible может быть меньше.'),
  _Item('Wrap зачем?',
      'Перенос чипов/тегов на следующую строку вместо overflow Row.'),
  _Item('CustomScrollView / slivers?',
      'Ленивые куски скролла: SliverAppBar, SliverList, SliverGrid в одном viewport.'),
  _Item('AspectRatio / FractionallySizedBox?',
      'Жёсткое соотношение сторон; доля от родителя.'),
  _Item('OverflowBox / IgnorePointer — когда?',
      'OverflowBox позволяет ребёнку выйти за constraints (осторожно). IgnorePointer отключает hit-testing.'),
  _Item('Dismissible?',
      'Swipe-to-dismiss; обязателен Key для корректной идентичности в списке.'),
]);

const _scrolling = _Qa('Scrolling', [
  _Item('ListView vs ListView.builder?',
      'builder ленивый — создаёт детей по мере скролла. Обычный ListView строит всех детей сразу.'),
  _Item('ScrollController зачем и dispose?',
      'Слушать offset, jump/animateTo. Обязательно dispose, иначе утечки.'),
  _Item('RefreshIndicator требования?',
      'Scrollable должен уметь overscroll; часто нужен AlwaysScrollableScrollPhysics для коротких списков.'),
  _Item('Как детектить конец списка (pagination)?',
      'Слушать metrics: `pixels >= maxScrollExtent - threshold` или NotificationListener.'),
  _Item('PageView vs TabBarView?',
      'PageView — страницы жестом. TabBarView связан с TabController.'),
  _Item('PrimaryScrollController?',
      'Общий контроллер для scaffold/scroll; конфликт двух primary scrollables.'),
  _Item('NestedScrollView когда?',
      'Связка header sliver + внутренний tab scroll.'),
  _Item('ScrollNotification типы?',
      'Start/Update/End/Overscroll — для custom эффектов и load-more.'),
]);

const _images = _Qa('Images', [
  _Item('Image.asset vs Image.network?',
      'Asset из бандла; network грузит по URL (кэш в памяти/диске ограниченно).'),
  _Item('BoxFit.cover vs contain vs fill?',
      'cover — заполнить с обрезкой; contain — целиком без обрезки; fill — растянуть с искажением.'),
  _Item('Зачем loadingBuilder/errorBuilder?',
      'Placeholder на загрузке и UI ошибки вместо пустоты/краша.'),
  _Item('AspectRatio для картинок?',
      'Резервирует место, уменьшает layout jump до загрузки.'),
  _Item('Cached network image?',
      'Пакет `cached_network_image` для дискового кэша; на собесе — упомянуть memory pressure.'),
  _Item('Resolution-aware assets?',
      '`1.5x/2.0x/3.0x` папки; Flutter выбирает по devicePixelRatio.'),
  _Item('FadeInImage?',
      'Плавная смена placeholder → картинка.'),
  _Item('Большие изображения и OOM?',
      '`cacheWidth/cacheHeight`, сжатие, isolates для decode тяжёлого.'),
]);

const _forms = _Qa('Forms и валидация', [
  _Item('Form + GlobalKey<FormState> зачем?',
      '`validate()`, `save()`, `reset()` централизованно.'),
  _Item('TextEditingController lifecycle?',
      'Создать в State, dispose обязательно.'),
  _Item('autovalidateMode варианты?',
      'disabled / always / onUserInteraction — UX валидации.'),
  _Item('FocusNode в формах?',
      'Переход next/done, программный фокус, accessibility.'),
  _Item('Как делать async submit?',
      'Блокировать кнопку, показывать progress, не вызывать validate после dispose; проверить mounted.'),
  _Item('Debounce поиска?',
      'Timer на onChanged; сброс предыдущего; dispose timer.'),
  _Item('Валидатор возвращает что?',
      '`String?`: null — ок, строка — текст ошибки.'),
  _Item('Отличие FormField и TextFormField?',
      'TextFormField — удобная обёртка FormField для текста.'),
]);

const _overlays = _Qa('SnackBar, Dialog, BottomSheet', [
  _Item('ScaffoldMessenger vs Scaffold.of?',
      'Messenger переживает смену Scaffold (навигация); современный способ SnackBar.'),
  _Item('showDialog возвращает Future?',
      'Да, результат `Navigator.pop(context, value)`. null если dismiss barrier.'),
  _Item('barrierDismissible?',
      'Тап вне диалога закрывает. Для destructive — часто false.'),
  _Item('Modal vs ordinary bottom sheet?',
      'Modal блокирует остальной UI (`showModalBottomSheet`). Persistent — часть scaffold.'),
  _Item('Как прокинуть результат из sheet?',
      '`Navigator.pop(context, result)` / `await showModalBottomSheet<T>`.'),
  _Item('Диалог и async gap + context?',
      'После await проверить `context.mounted` перед новым UI.'),
  _Item('Snackbar action?',
      'Undo/Retry через `SnackBarAction`; не держать долго критичный state только там.'),
  _Item('rootNavigator в dialog?',
      'Показывает над всем стеком маршрутов; важно при nested navigators.'),
]);

const _theming = _Qa('Theming Material 3', [
  _Item('ThemeData vs ColorScheme?',
      'ColorScheme — палитра ролей; ThemeData собирает component themes + typography.'),
  _Item('ThemeExtension зачем?',
      'Свои токены (spacing, brand) с lerp/copyWith, доступ через `Theme.of(context).extension<T>()`.'),
  _Item('light/dark переключение?',
      '`ThemeMode` + `MaterialApp.theme/darkTheme`. Слушать platform brightness.'),
  _Item('Как локально переопределить тему?',
      '`Theme(data: Theme.of(context).copyWith(...), child: ...)`.'),
  _Item('TextTheme роли?',
      'display/headline/title/body/label — семантические стили M3.'),
  _Item('seedColor в ColorScheme.fromSeed?',
      'Генерирует гармоничную палитру M3 из одного seed.'),
  _Item('Не хардкодить Colors.blue в фичах?',
      'Брать из ColorScheme (`primary`, `surface`…) для dark mode и консистентности.'),
  _Item('Dynamic color/Android 12+?',
      'Можно подтягивать wallpaper colors (пакеты/platform) — плюс на senior-собесе.'),
]);

const _widgetKeys = _Qa('Widget Keys', [
  _Item('Зачем Key в Flutter?',
      'Сохранять Element/State при перемещении виджета в дереве; корректные анимации/формы/списки.'),
  _Item('ValueKey vs ObjectKey vs UniqueKey?',
      'ValueKey — по значению (id). ObjectKey — по identity объекта. UniqueKey — всегда новый, сбрасывает state.'),
  _Item('Почему index плохой Key?',
      'При insert/delete/sort индексы съезжают → State прилипает не к тем данным.'),
  _Item('GlobalKey когда?',
      'Доступ к State (`FormState`), измерению, редким случаям. Дорого и ломает инкапсуляцию — не злоупотреблять.'),
  _Item('LocalKey?',
      'Базовый тип для Value/Object/Unique — в рамках родителя.'),
  _Item('Ключи и AnimatedList / ReorderableListView?',
      'Нужны стабильные ключи для анимаций перемещения.'),
  _Item('можно ли один GlobalKey на два места?',
      'Нет, один GlobalKey — один элемент в дереве.'),
  _Item('Key не нужно вешать на всё?',
      'Только где важна идентичность при структурных изменениях.'),
]);

const _animations = _Qa('Animations', [
  _Item('Implicit vs explicit animations?',
      'Implicit (`AnimatedContainer`) — сами анимируют при смене полей. Explicit — `AnimationController` + Tween.'),
  _Item('Зачем Ticker / SingleTickerProviderStateMixin?',
      'Vsync сигналы для controller; один ticker — Single, несколько — TickerProviderStateMixin.'),
  _Item('Dispose AnimationController?',
      'Обязателен, иначе ticker leak / assert.'),
  _Item('Tween / Curve / Interval?',
      'Tween — интерполяция begin/end. Curve — easing. Interval — кусок timeline 0..1.'),
  _Item('AnimatedBuilder vs AnimatedWidget?',
      'Builder удобнее без subclass; слушает Listenable и перестраивает.'),
  _Item('AnimationStatus?',
      'dismissed/forward/reverse/completed — реакция на конец/направление.'),
  _Item('Hero анимации?',
      'Shared element между routes по одному `tag`.'),
  _Item('Производительность анимаций?',
      'Избегать тяжёлого build; анимировать transform/opacity; по возможности на GPU.'),
]);

const _navigation = _Qa('go_router / Navigation', [
  _Item('Imperative vs declarative navigation?',
      'Imperative: `push/pop`. Declarative: URL/state → page stack (go_router).'),
  _Item('path vs query params?',
      'Path — идентичность ресурса `/users/:id`. Query — фильтры/табы `?tab=posts`.'),
  _Item('redirect в go_router?',
      'Auth guards, onboarding, канонизация URL. Выполняется при навигации/refresh.'),
  _Item('ShellRoute зачем?',
      'Общий scaffold (bottom nav) с вложенными ветками навигации.'),
  _Item('extra vs path params?',
      'extra — объект в памяти (не глубоко линкуется). Path/query — serializable URL.'),
  _Item('errorBuilder?',
      '404/невалидный route UI.'),
  _Item('refreshListenable?',
      'Пересчёт redirect при смене auth/state.'),
  _Item('Deep link + redirect типичный баг?',
      'Затирать intended URL; нужно сохранять redirect query и вернуть после login.'),
]);

const _responsive = _Qa('Responsive / Adaptive', [
  _Item('Responsive vs adaptive?',
      'Responsive — тянется layout. Adaptive — меняет UX-паттерн (NavigationRail vs BottomBar).'),
  _Item('Breakpoints откуда брать?',
      'Material window size classes / свои 600/840; лучше LayoutBuilder чем «магический MediaQuery везде».'),
  _Item('Master-detail на больших экранах?',
      'Две панели: список + детали; на compact — stack navigation.'),
  _Item('Orientation?',
      '`OrientationBuilder` / MediaQuery.orientation; не дублировать бизнес-логику.'),
  _Item('Text scaling / accessibility?',
      'Учитывать `MediaQuery.textScaler`; не фиксировать высоты текста жёстко.'),
  _Item('SafeArea / viewInsets?',
      'Вырезы и клавиатура; padding от MediaQuery.viewInsets.'),
  _Item('Когда использовать FittedBox?',
      'Масштаб ребёнка в доступный бокс; осторожно с читаемостью.'),
  _Item('Тестирование adaptive UI?',
      'Widget тесты с разными surface size / golden tests.'),
]);

const _a11y = _Qa('Accessibility', [
  _Item('Минимальный tap target?',
      'Около 48x48 dp по Material; проверять Semantics/hit area.'),
  _Item('Semantics виджет зачем?',
      'Явные label/value/button/hint для screen readers.'),
  _Item('ExcludeSemantics / MergeSemantics?',
      'Убрать шум; объединить детей в один semantic node.'),
  _Item('Цветовой контраст?',
      'Текст/иконки достаточный contrast ratio; не опираться только на цвет.'),
  _Item('Keyboard / focus traversal?',
      'Важен для desktop/web: FocusTraversalGroup, order, skipTraversal.'),
  _Item('Announce для TalkBack/VoiceOver?',
      'SemanticsService.announce / live regions для динамических сообщений.'),
  _Item('Как тестировать a11y?',
      '`tester.ensureSemantics()`, проверки label, `meetsGuideline`.'),
  _Item('decorative images?',
      'Помечать exclude semantics, чтобы не читались.'),
]);

const _focus = _Qa('Focus', [
  _Item('FocusNode vs FocusScope?',
      'Node — фокус конкретного контрола. Scope — область обхода/primary focus subtree.'),
  _Item('requestFocus / unfocus?',
      'Программный фокус; unfocus снимает primary focus (часто при тапе вне поля).'),
  _Item('TextInputAction.next?',
      'Кнопка клавиатуры «далее» → focus следующего поля.'),
  _Item('Обязателен dispose FocusNode?',
      'Да, если создаёте сами в State.'),
  _Item('canRequestFocus?',
      'false для disabled полей — не участвует в traversal.'),
  _Item('FocusTraversalPolicy?',
      'Порядок обхода Tab: ReadingOrder/Ordered/WidgetOrder; NumericFocusOrder.'),
  _Item('autofocus?',
      'Запрос фокуса при первом frame; не злоупотреблять на сложных экранах.'),
  _Item('Focus и accessibility?',
      'Видимый focus indicator важен для клавиатурных пользователей.'),
]);

const _networking = _Qa('Networking', [
  _Item('http vs dio?',
      'http — простой. dio — interceptors, cancel, FormData. На собесе важны таймауты/ошибки/ретраи.'),
  _Item('Идемпотентность и retry?',
      'Retry безопасно на GET/idempotent; осторожно с POST. Коды 408/429/5xx — кандидаты.'),
  _Item('Где держать baseUrl и token?',
      'Конфиг/env + secure storage для token; interceptor добавляет Authorization.'),
  _Item('Таймауты?',
      'connect/receive timeout; UX cancel; различать network vs server error.'),
  _Item('Сериализация ошибок API?',
      'Единый `ApiException(status, message)` / Either Left; парсить body `message`.'),
  _Item('Certificate pinning — знаете?',
      'Защита от MITM; сложность ротации сертификатов — middle/senior тема.'),
  _Item('Пагинация?',
      'page/cursor; sync со scroll load-more; не дублировать запросы (in-flight flag).'),
  _Item('Тестирование клиента?',
      'Мок transport/adapter; golden contract tests на JSON fixtures.'),
]);

const _storage = _Qa('Local Storage', [
  _Item('SharedPreferences vs secure storage vs DB?',
      'Prefs — простые ключи. Secure — токены. Hive/Drift/SQLite — структурированные данные.'),
  _Item('Что нельзя хранить в prefs?',
      'Секреты в plaintext, большие blob без необходимости.'),
  _Item('Миграции ключей?',
      'Версия схемы/флаг миграции; перенос old→new и удаление old.'),
  _Item('JSON в prefs?',
      'encode/decode строки; версионировать модель настроек.'),
  _Item('Многопоточность/isolates и prefs?',
      'Плагины часто main-isolate; не считать потокобезопасным везде.'),
  _Item('Clear on logout?',
      'Удалить token и user-scoped данные; сохранить onboarding flags если нужно.'),
  _Item('Типы значений prefs?',
      'string/int/bool/double/stringList — остальное сериализуйте.'),
  _Item('Тестирование storage?',
      'In-memory fake implementing тот же интерфейс.'),
]);

const _notifications = _Qa('Local Notifications', [
  _Item('Local vs push notifications?',
      'Local — устройство само показывает. Push — FCM/APNs с сервера.'),
  _Item('Android notification channel зачем?',
      'С Android 8 канал определяет важность/звук; пользователь управляет в настройках.'),
  _Item('iOS category / actions?',
      'Кнопки действий регистрируются в category; уведомление ссылается на categoryId.'),
  _Item('Permissions Android 13+ / iOS?',
      'Нужен runtime permission; иначе уведомления не видны.'),
  _Item('payload зачем?',
      'Строка для навигации/id сущности при тапе/action.'),
  _Item('Foreground presentation?',
      'На iOS настроить presentAlert/banner; на Android поведение канала/importance.'),
  _Item('Тап по телу vs action button?',
      'actionId пустой/null → tap; иначе id кнопки. Разный UX.'),
  _Item('Инициализация плагина?',
      'Один раз после binding; создать каналы до show; обработчики background/terminated отдельно продумать.'),
]);

const _pushNotifications = _Qa('Push Notifications', [
  _Item('Чем push отличается от локального уведомления?',
      'Local показывает само приложение через ОС. Push идёт с сервера через FCM; на iOS видимый баннер доставляет APNs.'),
  _Item('Зачем FCM-токен и что делать на onTokenRefresh и logout?',
      'Токен — адрес установки на устройстве. `onTokenRefresh` шлёт новый токен на бэкенд. На logout связку удаляют на сервере и вызывают `deleteToken`, иначе следующий аккаунт получит чужие сообщения.'),
  _Item('Чем notification, data и both отличаются по показу баннера?',
      'Notification в фоне рисует система, Dart при доставке не вызывается. Data молчит, его обрабатывает код. Both: система рисует текст, data доступна обработчику.'),
  _Item('Какие callback в foreground, background и terminated?',
      'Foreground — всегда `onMessage`. Background/terminated: notification → трей, data → `onBackgroundMessage`, both → трей и background-handler. Тап — отдельно.'),
  _Item(
      'Почему onBackgroundMessage — top-level функция с @pragma(\'vm:entry-point\'), зарегистрированная до runApp?',
      'Обработчик живёт в другом изоляте. Замыкание и метод объекта туда не попадут, tree shaking вырежет функцию без pragma, поздняя регистрация после `runApp` пропускает сообщение.'),
  _Item('Чем onMessageOpenedApp отличается от getInitialMessage?',
      '`onMessageOpenedApp` — тап, когда процесс был в background. `getInitialMessage` — один раз при холодном старте из terminated. Оба читают одну data.'),
  _Item('Почему в foreground баннер часто рисуют через flutter_local_notifications?',
      'В foreground система баннер не показывает. `onMessage` получает payload, а видимый alert рисует локальный плагин со своим каналом и кнопками.'),
  _Item('Зачем collapse key и чем high priority отличается от normal?',
      'Одинаковый collapse key оставляет в трее последнее сообщение. `high` будит устройство (чат, звонок). `normal` можно отложить — для дайджеста. Маркетинг с high сажает батарею и упирается в квоты FCM.'),
  _Item('Когда подписка на topic уместнее рассылки по токенам?',
      'Топик — одна рассылка многим подписчикам (новости). Личное сообщение шлют на токен конкретного устройства.'),
  _Item('Что нельзя класть в data payload?',
      'Секреты, access token, лишние персональные данные. Payload виден в логах и у провайдера. Для навигации хватает id или внутреннего route.'),
]);

const _permissions = _Qa('Permissions', [
  _Item('Статусы permission?',
      'granted/denied/permanentlyDenied/restricted/limited — разные UX.'),
  _Item('Когда открывать настройки приложения?',
      'permanentlyDenied / повторный deny без диалога — вести в App Settings.'),
  _Item('Rationale dialog зачем?',
      'Объяснить зачем permission до system prompt (особенно Android).'),
  _Item('limited photos на iOS?',
      'Частичный доступ; UI должен уметь работать с subset.'),
  _Item('Не запрашивать всё на старте?',
      'Запрашивать contextual just-in-time — выше convert и доверие.'),
  _Item('Связь permission и feature flag?',
      'FeatureAccess: allowed / needsRequest / needsSettings / unavailable.'),
  _Item('Тестирование?',
      'Fake PermissionGateway со статусами.'),
  _Item('POST_NOTIFICATIONS?',
      'Android 13+ отдельное permission для уведомлений.'),
]);

const _lifecycle = _Qa('App Lifecycle', [
  _Item('AppLifecycleState основные?',
      'resumed/inactive/paused/detached/hidden — смысл для sync/pause.'),
  _Item('WidgetsBindingObserver?',
      'Подписка на `didChangeAppLifecycleState` в State; add/remove observer.'),
  _Item('Что делать в paused/hidden?',
      'Сохранить черновик, пауза плеера/websocket sync, освободить камеру.'),
  _Item('inactive vs paused?',
      'inactive — кратковременно (звонок/CC). paused — фон.'),
  _Item('Сохранение state vs restoration?',
      'Черновик в storage; RestorationMixin — OS-level UI restoration.'),
  _Item('Нельзя полагаться только на dispose?',
      'Процесс могут убить; persist критичное раньше (на pause).'),
  _Item('Flutter 3 hidden?',
      'UI не виден, но ещё не обязательно paused — учитывайте в логике.'),
  _Item('Тесты lifecycle?',
      'Симулировать события binding / свои контроллеры состояний.'),
]);

const _deepLinks = _Qa('Deep Links', [
  _Item('Deep link vs universal/app link?',
      'Custom scheme `myapp://`. Universal/App Links — https домен с verification.'),
  _Item('Почему https лучше custom scheme?',
      'Безопаснее (domain ownership), лучше UX из браузера/почты.'),
  _Item('Парсинг в go_router?',
      'URL → route match → path/query params; остальное в redirect.'),
  _Item('Auth + deep link?',
      'Сохранить intended location, на login redirect query, после auth вернуться.'),
  _Item('Нормализация path?',
      'Trailing slash, www, http→https — канонизировать чтобы не плодить маршруты.'),
  _Item('Невалидный deep link?',
      'error/fallback home; не крашить приложение.'),
  _Item('Android/iOS конфигурация?',
      'intent-filters / apple-app-site-association — на собесе упомянуть.'),
  _Item('Тестирование?',
      'Unit parse/match + integration открытие URI.'),
]);

const _localization = _Qa('Localization (i18n)', [
  _Item('ARB + gen-l10n vs ручной словарь?',
      'Официальный путь Flutter — ARB/codegen. Ручной — для обучения концепций.'),
  _Item('Locale resolution?',
      'Выбрать лучший из device locales среди supported, иначе fallback (часто en).'),
  _Item('Plural rules?',
      'CLDR: en one/other; ru one/few/many — не хардкодить `count==1` для всех языков.'),
  _Item('Плейсхолдеры?',
      'Именованные `{name}` / ICU messages; не конкатенировать предложения.'),
  _Item('RTL?',
      '`Directionality`, EdgeInsets directional, не зеркалить всё бездумно.'),
  _Item('Дата/число форматы?',
      '`intl` DateFormat/NumberFormat по locale.'),
  _Item('Over-localization строк в коде?',
      'Все user-facing в l10n; логи/ключи ошибок — отдельно.'),
  _Item('Тесты l10n?',
      'Прогон lookup/plural для нескольких locales.'),
]);

const _errorsJuniors = _Qa('Типичные ошибки Junior Flutter', [
  _Item('setState during build — почему плохо?',
      'Рекурсивные rebuilds / assert. Планировать обновление post-frame или менять state вне build.'),
  _Item('async + context без mounted?',
      'Виджет мог dispose → crash. Проверять `mounted`/`context.mounted`.'),
  _Item('Future в build FutureBuilder?',
      'Пересоздание Future → повторные запросы. Кэшировать Future.'),
  _Item('Забыли dispose controller?',
      'Утечки и warnings. Controllers/FocusNode/AnimationController — dispose.'),
  _Item('ListView в Column unbounded?',
      'Нужен Expanded/SizedBox/shrinkWrap с пониманием цены.'),
  _Item('Использовать context в initState для Inherited?',
      'Зависит: лучше `didChangeDependencies` для MediaQuery/Provider of.'),
  _Item('Мутация state без setState/notifier?',
      'UI не обновится.'),
  _Item('Гигантские build методы?',
      'Ребилд всего экрана; дробить виджеты, const, селекторы state.'),
]);

const _changeNotifier = _Qa('ChangeNotifier', [
  _Item('Как работает ChangeNotifier?',
      'Хранит listeners; `notifyListeners()` синхронно вызывает их.'),
  _Item('ValueNotifier vs ChangeNotifier?',
      'ValueNotifier — одно value + notify при set. ChangeNotifier — произвольная модель.'),
  _Item('Обязателен dispose?',
      'Да для своих notifier/animation; снять listeners.'),
  _Item('Listenable.merge?',
      'Слушать несколько listenables как один.'),
  _Item('Связь с Provider/Riverpod?',
      'Provider исторически часто оборачивал ChangeNotifier. Riverpod — другой runtime, но идея подписки та же.'),
  _Item('Опасность notify в destructor?',
      'Не уведомлять после dispose — assert/fail.'),
  _Item('Когда хватит ValueNotifier?',
      'Один примитив/флаг UI без сложной логики.'),
  _Item('Тестирование notifier?',
      'addListener + expect value; без UI.'),
]);

const _architecture = _Qa('Architecture (domain/data/presentation)', [
  _Item('Что такое clean/layered architecture во Flutter?',
      'Разделение presentation / domain / data. Зависимости внутрь: UI → domain ← data.'),
  _Item('Где жить JSON?',
      'Только data (DTO). Domain — чистые entity/use-cases.'),
  _Item('Repository pattern?',
      'Абстракция источника данных для domain; реализации: api/db/cache.'),
  _Item('Use-case/interactor зачем?',
      'Одна бизнес-операция (AddTodo); удобно тестировать и переиспользовать.'),
  _Item('Ошибки как значения?',
      'sealed Failure + Either/TaskEither вместо throw через слои.'),
  _Item('Может ли domain импортировать Flutter?',
      'Желательно нет — переносимость и тесты без binding.'),
  _Item('Presentation state?',
      'loading/data/error (AsyncValue/ViewState); маппинг Failure→message.'),
  _Item('Зачем interfaces на границах?',
      'Подмена фейков в тестах; независимость от Dio/Prefs деталей.'),
]);

const _riverpod = _Qa('Riverpod', [
  _Item('Provider vs Riverpod?',
      'Riverpod compile-safe, нет зависимости от BuildContext для чтения, лучше тестируется, codegen.'),
  _Item('ref.watch vs read vs listen?',
      'watch — подписка/rebuild. read — разово (callbacks). listen — side effects.'),
  _Item('Notifier / AsyncNotifier?',
      'Класс с `build()` state; методы меняют state. Async — для Future.'),
  _Item('autoDispose зачем?',
      'Освобождать state без слушателей; кэш сбрасывается — помнить про keepAlive.'),
  _Item('Family providers?',
      'Параметризованные провайдеры `provider(id)`.'),
  _Item('Override в тестах?',
      '`ProviderContainer(overrides: [...])` / ProviderScope overrides.'),
  _Item('Не делать side effects в build провайдера?',
      'build должен быть чистым; сеть — через AsyncNotifier/методы.'),
  _Item('Riverpod codegen аннотации?',
      '`@riverpod` / `@Riverpod(keepAlive: true)` → генерация `*Provider`.'),
]);

const _fpdartRiverpod = _Qa('fpdart + Riverpod', [
  _Item('Как связать TaskEither и AsyncValue?',
      'run task → fold в AsyncData/AsyncError или helper `taskToAsyncValue`.'),
  _Item('Где выполнять TaskEither?',
      'В Notifier/repository use-case; UI только смотрит AsyncValue.'),
  _Item('Показывать SnackBar при Left?',
      'ref.listen на AsyncValue/ошибку; не в build.'),
  _Item('Retry UX?',
      'Кнопка повтора вызывает метод notifier снова; сохранить args.'),
  _Item('Не протекать fpdart типы в UI?',
      'UI знает ViewState/AsyncValue; Either остаётся в application/data.'),
  _Item('Параллельные запросы?',
      'parallel TaskEither / Future.wait → один AsyncValue комбинированного результата.'),
  _Item('Кэширование успешных Right?',
      'keepAlive / ручной cache в repository; инвалидация на mutate.'),
  _Item('Тесты связки?',
      'Фейковый repo возвращает Left/Right; container.read notifier.'),
]);

const _promptEngineering = _Qa('Prompt Engineering', [
  _Item('Что такое хороший промпт для кода?',
      'Роль, контекст, цель, ограничения, формат ответа, примеры (few-shot).'),
  _Item('Few-shot vs zero-shot?',
      'Few-shot даёт примеры желаемого поведения; лучше для форматов/стиля.'),
  _Item('Chain of Thought?',
      'Просьба рассуждать по шагам для сложной логики; для кода — план→патч.'),
  _Item('Как просить рефакторинг безопасно?',
      'Сохранить поведение, указать тесты, маленький diff, не менять публичный API без нужды.'),
  _Item('Контекстное окно — практика?',
      'Давать релевантные файлы/сигнатуры, не весь репозиторий.'),
  _Item('Системный промпт?',
      'Стабильные правила ассистента (стиль, стек, запреты).'),
  _Item('Итерации vs один гигантский запрос?',
      'Часто лучше уточнять по шагам с проверкой тестами.'),
  _Item('Галлюцинации модели?',
      'Требовать опираться на присланный код; проверять API по docs/анализатору.'),
]);

const _miniApps = _Qa('Mini Apps', [
  _Item('С чего начать mini-app?',
      'Доменные модели + repository + тесты, затем state, затем UI.'),
  _Item('Как разделить fake API и UI?',
      'Интерфейс репозитория; delayed fake; UI на AsyncValue.'),
  _Item('Auth flow минимальный критерий?',
      'redirect на login, сохранение сессии, возврат на intended route.'),
  _Item('Корзина: какой state?',
      'Нормализованный Map id→qty, derived totals; один source of truth.'),
  _Item('Обработка empty/loading/error?',
      'Явные ветки UI; retry; не оставлять blank screen.'),
  _Item('Когда выносить в package/layer?',
      'Когда появляется повтор и тесты тормозят из-за UI связности.'),
  _Item('fpdart в mini-app — где граница?',
      'Ошибки домена в Either; UI fold/AsyncValue.'),
  _Item('Definition of Done mini-app?',
      'Сценарии happy/edge покрыты тестами логики + ручной прогон UI.'),
]);
